import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = resolve(packageRoot, "../../sdk/protocol-schema.json");
const fixturesPath = resolve(packageRoot, "../../sdk/protocol-fixtures.json");
const outputPath = resolve(packageRoot, "src/generated.ts");
const schemaBytes = await readFile(schemaPath);
const fixtureBytes = await readFile(fixturesPath);
const schema = JSON.parse(schemaBytes.toString("utf8"));
const fixtures = JSON.parse(fixtureBytes.toString("utf8"));

if (schema.format !== "headless-sdk-contract" || schema.schemaVersion !== 1) {
  throw new Error("unsupported Headless SDK schema");
}
if (typeof schema.protocolVersion !== "string" || !Array.isArray(schema.commands)) {
  throw new Error("invalid Headless SDK schema");
}
if (fixtures.schemaVersion !== schema.schemaVersion
  || fixtures.protocolVersion !== schema.protocolVersion) {
  throw new Error("protocol fixtures do not match the SDK schema");
}
if (!Array.isArray(schema.localLifecycle?.launch?.argv)
  || !Array.isArray(schema.localLifecycle.launch.options)) {
  throw new Error("schema has no supervised launch contract");
}
const presentationOption = schema.localLifecycle.launch.options
  .find((option) => option.name === "presentation");
if (!Array.isArray(presentationOption?.values)
  || presentationOption.values.length === 0
  || !presentationOption.values.includes("background")) {
  throw new Error("schema has no valid launch presentation contract");
}

function identifier(value) {
  return value.split(/[^A-Za-z0-9]+/).filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

function methodName(command) {
  const parts = command.split(".");
  return parts[0] + parts.slice(1).map(identifier).join("");
}

function literal(value) {
  return JSON.stringify(value);
}

function parameterType(parameter) {
  if (Array.isArray(parameter.values) && !parameter.caseInsensitiveValues) {
    return parameter.values.map(literal).join(" | ");
  }
  switch (parameter.type) {
  case "boolean": return "boolean";
  case "integer":
  case "number": return "number";
  case "string-array": return "readonly string[]";
  case "string": return "string";
  default: throw new Error(`unsupported parameter type: ${parameter.type}`);
  }
}

function resultType(type) {
  switch (type) {
  case "array": return "readonly JsonValue[]";
  case "boolean": return "boolean";
  case "json": return "JsonValue";
  case "number": return "number";
  case "object": return "Readonly<Record<string, JsonValue>>";
  case "string": return "string";
  case "string-or-null": return "string | null";
  default: throw new Error(`unsupported result type: ${type}`);
  }
}

const resultSchemas = new Map();
function registerResultSchema(result, label) {
  const name = result?.name;
  if (!name || !Array.isArray(result.fields)) throw new Error(`invalid result schema: ${label}`);
  const encoded = JSON.stringify(result);
  const previous = resultSchemas.get(name);
  if (previous && previous !== encoded) throw new Error(`conflicting result schema: ${name}`);
  resultSchemas.set(name, encoded);
}

for (const command of schema.commands) {
  const name = command.result?.schema?.name;
  if (!name || !["host", "session"].includes(command.scope)
    || typeof command.timeout?.defaultMilliseconds !== "number"
    || !Array.isArray(command.parameters) || !Array.isArray(command.result.schema.fields)) {
    throw new Error(`invalid command schema: ${command.name}`);
  }
  registerResultSchema(command.result.schema, command.name);
}

if (!schema.errorDetails || typeof schema.errorDetails !== "object") {
  throw new Error("schema has no error detail contracts");
}
for (const [code, details] of Object.entries(schema.errorDetails)) {
  registerResultSchema(details.schema, code);
}

const lines = [
  "// Generated by scripts/generate-sdk.mjs. Do not edit.",
  "",
  "export type JsonPrimitive = boolean | number | string | null;",
  "export type JsonValue = JsonPrimitive | readonly JsonValue[] | { readonly [key: string]: JsonValue };",
  "export type Untrusted<T> = Readonly<{ readonly untrustedContent: true; readonly value: T }> ;",
  "",
  `export const PROTOCOL_VERSION = ${literal(schema.protocolVersion)} as const;`,
  `export const PROTOCOL_SCHEMA_VERSION = ${schema.schemaVersion} as const;`,
  `export const MAXIMUM_MESSAGE_BYTES = ${schema.maximumMessageBytes} as const;`,
  `export const PROTOCOL_SCHEMA_SHA256 = ${literal(createHash("sha256").update(schemaBytes).digest("hex"))} as const;`,
  `export const PROTOCOL_FIXTURES_SHA256 = ${literal(createHash("sha256").update(fixtureBytes).digest("hex"))} as const;`,
  `export const RESPONSE_ADDITIONAL_PROPERTIES = ${schema.response.additionalProperties === true} as const;`,
  `export const MAXIMUM_COMMAND_TIMEOUT_MS = ${Math.max(...schema.commands.flatMap((command) => [
    command.timeout.defaultMilliseconds,
    command.timeout.maximumMilliseconds ?? 0,
    ...Object.values(command.timeout.parameterPresentOverrides),
  ]))} as const;`,
  `export const LOCAL_LIFECYCLE = ${JSON.stringify(schema.localLifecycle, null, 2)} as const;`,
  `export const LAUNCH_PRESENTATIONS = ${JSON.stringify(presentationOption.values)} as const;`,
  `export type LaunchPresentation = typeof LAUNCH_PRESENTATIONS[number];`,
  "",
  "export interface CommandOptions {",
  "  readonly signal?: AbortSignal;",
  "  readonly timeoutMs?: number;",
  "}",
  "",
];

for (const command of schema.commands) {
  const typeName = `${identifier(command.name)}Parameters`;
  lines.push(`export interface ${typeName} {`);
  for (const parameter of command.parameters) {
    lines.push(`  readonly ${JSON.stringify(parameter.name)}${parameter.required ? "" : "?"}: ${parameterType(parameter)};`);
  }
  lines.push("}", "");
}

for (const encoded of resultSchemas.values()) {
  const result = JSON.parse(encoded);
  lines.push(`export interface ${result.name} {`);
  for (const field of result.fields) {
    lines.push(`  readonly ${JSON.stringify(field.name)}${field.required ? "" : "?"}: ${resultType(field.type)};`);
  }
  if (result.additionalProperties) lines.push("  readonly [key: string]: JsonValue;");
  lines.push("}", "");
}

const errorCodes = schema.response?.failure?.error?.codes;
if (!Array.isArray(errorCodes) || errorCodes.length === 0) throw new Error("schema has no error codes");
const lifecycleErrorCodes = schema.localLifecycle.launch.errors;
if (!Array.isArray(lifecycleErrorCodes) || lifecycleErrorCodes.length === 0) {
  throw new Error("schema has no lifecycle error codes");
}
lines.push(
  `export type CommandErrorCode = ${errorCodes.map(literal).join(" | ")};`,
  "",
  `export type LifecycleErrorCode = ${lifecycleErrorCodes.map(literal).join(" | ")};`,
  "",
  `export const LIFECYCLE_ERROR_CODES = ${JSON.stringify(lifecycleErrorCodes)} as const;`,
  "",
  "export interface ErrorDetails {",
);
for (const [code, details] of Object.entries(schema.errorDetails)) {
  const detailType = details.mayContainUntrustedContent
    ? `Untrusted<${details.schema.name}>`
    : details.schema.name;
  lines.push(`  readonly ${literal(code)}: ${detailType};`);
}
lines.push(
  "}",
  "",
  `export const ERROR_DETAILS_METADATA = ${JSON.stringify(schema.errorDetails, null, 2)} as const;`,
  "",
  `export type CommandName = ${schema.commands.map((command) => literal(command.name)).join(" | ")};`,
  "",
  "export interface CommandParameters {",
);
for (const command of schema.commands) {
  lines.push(`  readonly ${literal(command.name)}: ${identifier(command.name)}Parameters;`);
}
lines.push("}", "", "export interface CommandResults {");
for (const command of schema.commands) {
  const resultName = command.result.schema.name;
  const result = command.result.mayContainUntrustedContent ? `Untrusted<${resultName}>` : resultName;
  lines.push(`  readonly ${literal(command.name)}: ${result};`);
}
lines.push(
  "}",
  "",
  "export type CommandResult<C extends CommandName> = CommandResults[C];",
  "",
  `export const COMMAND_METADATA = ${JSON.stringify(Object.fromEntries(schema.commands.map((command) => [command.name, {
    capabilityNegotiated: command.capabilityNegotiated,
    parameters: command.parameters,
    result: command.result,
    scope: command.scope,
    timeout: command.timeout,
  }])), null, 2)} as const;`,
  "",
  "export function commandTimeoutMilliseconds<C extends CommandName>(",
  "  command: C,",
  "  parameters: CommandParameters[C],",
  "): number {",
  "  const policy = COMMAND_METADATA[command].timeout;",
  "  for (const [parameter, timeout] of Object.entries(policy.parameterPresentOverrides)) {",
  "    if ((parameters as Readonly<Record<string, unknown>>)[parameter] !== undefined) return timeout;",
  "  }",
  "  if (\"parameterName\" in policy) {",
  "    const value = (parameters as Readonly<Record<string, unknown>>)[policy.parameterName];",
  "    if (typeof value === \"number\") {",
  "      return Math.max(",
  "        policy.minimumMilliseconds,",
  "        Math.min(policy.maximumMilliseconds, value + policy.parameterGraceMilliseconds),",
  "      );",
  "    }",
  "  }",
  "  return policy.defaultMilliseconds;",
  "}",
  "",
  "export abstract class GeneratedCommandClient {",
  "  protected abstract invoke<C extends CommandName>(",
  "    command: C,",
  "    parameters: CommandParameters[C],",
  "    options?: CommandOptions,",
  "  ): Promise<CommandResult<C>>;",
  "",
);
function emitMethods(commands) {
  for (const command of commands) {
  const parameters = `${identifier(command.name)}Parameters`;
  const result = `Promise<CommandResult<${literal(command.name)}>>`;
  const required = command.parameters.some((parameter) => parameter.required);
  if (command.parameters.length === 0) {
    lines.push(`  ${methodName(command.name)}(options?: CommandOptions): ${result} {`);
    lines.push(`    return this.invoke(${literal(command.name)}, {}, options);`, "  }", "");
  } else if (required) {
    lines.push(`  ${methodName(command.name)}(parameters: ${parameters}, options?: CommandOptions): ${result} {`);
    lines.push(`    return this.invoke(${literal(command.name)}, parameters, options);`, "  }", "");
  } else {
    lines.push(`  ${methodName(command.name)}(parameters: ${parameters} = {}, options?: CommandOptions): ${result} {`);
    lines.push(`    return this.invoke(${literal(command.name)}, parameters, options);`, "  }", "");
  }
  }
}
emitMethods(schema.commands);
lines.push(
  "}",
  "",
  "export abstract class GeneratedSessionCommandClient {",
  "  protected abstract invoke<C extends CommandName>(",
  "    command: C,",
  "    parameters: CommandParameters[C],",
  "    options?: CommandOptions,",
  "  ): Promise<CommandResult<C>>;",
  "",
);
emitMethods(schema.commands.filter((command) => command.scope === "session"));
lines.push("}", "");

const output = `${lines.join("\n")}\n`;
if (process.argv.includes("--check")) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== output) throw new Error("generated SDK declarations are stale; run npm run generate");
} else {
  await writeFile(outputPath, output);
}
