// Generated by scripts/generate-sdk.mjs. Do not edit.

export type JsonPrimitive = boolean | number | string | null;
export type JsonValue = JsonPrimitive | readonly JsonValue[] | { readonly [key: string]: JsonValue };
export type Untrusted<T> = Readonly<{ readonly untrustedContent: true; readonly value: T }> ;

export const PROTOCOL_VERSION = "0.5" as const;
export const PROTOCOL_SCHEMA_VERSION = 1 as const;
export const MAXIMUM_MESSAGE_BYTES = 1048576 as const;
export const PROTOCOL_SCHEMA_SHA256 = "c199f18185cfa05b5c16c9140e48e1f588c61188b5f2ea6fa58eea2ddc57dcbf" as const;
export const PROTOCOL_FIXTURES_SHA256 = "0b51ffaa2d3e3aaf0c32adcfeb02c180dcbe44face0d49e1c332b69f403ae062" as const;
export const RESPONSE_ADDITIONAL_PROPERTIES = true as const;
export const MAXIMUM_COMMAND_TIMEOUT_MS = 125000 as const;
export const LOCAL_LIFECYCLE = {
  "connect": {
    "errors": [
      "HOST_UNAVAILABLE"
    ],
    "ownership": "shared",
    "transport": "local-unix-socket"
  },
  "launch": {
    "argv": [
      "start",
      "--background",
      "--supervised"
    ],
    "command": "start",
    "errors": [
      "HOST_START_FAILED",
      "NAVIGATION_ALLOWLIST_CONFLICT",
      "UNSUPPORTED_BROWSER_RUNTIME",
      "UNSUPPORTED_CAPABILITY"
    ],
    "options": [
      {
        "name": "presentation",
        "required": false,
        "type": "string",
        "values": [
          "background",
          "foreground"
        ]
      },
      {
        "itemMaximumBytes": 300,
        "maximumItems": 32,
        "name": "allow",
        "required": false,
        "type": "string-array"
      },
      {
        "const": true,
        "name": "supervised",
        "required": true,
        "type": "boolean"
      }
    ],
    "ownership": "owned-only-after-response-pid-matches-launched-child",
    "result": {
      "additionalProperties": true,
      "fields": [
        {
          "name": "ready",
          "required": true,
          "type": "boolean"
        },
        {
          "name": "pid",
          "required": true,
          "type": "number"
        },
        {
          "name": "engine",
          "required": true,
          "type": "string"
        },
        {
          "name": "platform",
          "required": true,
          "type": "string"
        },
        {
          "name": "productVersion",
          "required": true,
          "type": "string"
        },
        {
          "name": "protocolVersion",
          "required": true,
          "type": "string"
        },
        {
          "name": "capabilities",
          "required": true,
          "type": "object"
        },
        {
          "name": "recordingAvailable",
          "required": true,
          "type": "boolean"
        },
        {
          "name": "artifactDirectory",
          "required": true,
          "type": "string"
        },
        {
          "name": "navigationAllowlist",
          "required": true,
          "type": "array"
        }
      ],
      "name": "HostStatus",
      "type": "object"
    }
  }
} as const;
export const LAUNCH_PRESENTATIONS = ["background","foreground"] as const;
export type LaunchPresentation = typeof LAUNCH_PRESENTATIONS[number];

export interface CommandOptions {
  readonly signal?: AbortSignal;
  readonly timeoutMs?: number;
}

export interface PingParameters {
}

export interface ShutdownParameters {
}

export interface ProfileClearParameters {
}

export interface SessionCreateParameters {
  readonly "name": string;
  readonly "isolated"?: boolean;
}

export interface SessionListParameters {
}

export interface SessionCloseParameters {
}

export interface VisitParameters {
  readonly "url": string;
}

export interface InspectParameters {
  readonly "interactive"?: boolean;
  readonly "text"?: boolean;
  readonly "context"?: "summary" | "outline" | "text" | "actions" | "full";
  readonly "task"?: string;
  readonly "within"?: string;
  readonly "limit"?: number;
  readonly "budget"?: number;
  readonly "depth"?: number;
}

export interface ClickParameters {
  readonly "target"?: string;
  readonly "role"?: string;
  readonly "name"?: string;
}

export interface FillParameters {
  readonly "target"?: string;
  readonly "role"?: string;
  readonly "name"?: string;
  readonly "value": string;
}

export interface UploadParameters {
  readonly "target"?: string;
  readonly "role"?: string;
  readonly "name"?: string;
  readonly "artifact": string;
}

export interface PressParameters {
  readonly "key": string;
}

export interface ScrollParameters {
  readonly "direction"?: "up" | "down" | "top" | "bottom";
  readonly "amount"?: number;
}

export interface BackParameters {
}

export interface ReloadParameters {
}

export interface WaitParameters {
  readonly "settled"?: boolean;
  readonly "url"?: string;
  readonly "text"?: string;
  readonly "timeoutMs"?: number;
}

export interface TourParameters {
  readonly "fullPage"?: boolean;
  readonly "pace"?: number;
}

export interface CaptureInfoParameters {
}

export interface ScreenshotParameters {
  readonly "target"?: string;
  readonly "role"?: string;
  readonly "name"?: string;
  readonly "fullPage"?: boolean;
  readonly "output"?: string;
  readonly "series"?: "viewport" | "section";
  readonly "outputPrefix"?: string;
  readonly "format"?: string;
  readonly "clipboard"?: boolean;
}

export interface ArtifactListParameters {
}

export interface RecordStartParameters {
  readonly "output"?: string;
  readonly "fps"?: number;
  readonly "format"?: string;
  readonly "quality"?: string;
}

export interface RecordStatusParameters {
}

export interface RecordStopParameters {
  readonly "output"?: string;
}

export interface QaReportParameters {
}

export interface QaClearParameters {
}

export interface ConsoleListParameters {
  readonly "level"?: "all" | "log" | "info" | "debug" | "warn" | "error" | "assert";
  readonly "limit"?: number;
}

export interface NetworkListParameters {
  readonly "failed"?: boolean;
  readonly "status"?: number;
  readonly "limit"?: number;
}

export interface NetworkGetParameters {
  readonly "requestId": string;
}

export interface StylesGetParameters {
  readonly "target"?: string;
  readonly "role"?: string;
  readonly "name"?: string;
  readonly "properties"?: readonly string[];
}

export interface CookiesListParameters {
  readonly "includeValues"?: boolean;
}

export interface StorageListParameters {
  readonly "scope"?: "local" | "session" | "all";
  readonly "includeValues"?: boolean;
}

export interface VisualCompareParameters {
  readonly "before": string;
  readonly "after": string;
  readonly "output"?: string;
}

export interface PerformanceGetParameters {
}

export interface AnimationListParameters {
}

export interface ReportCreateParameters {
  readonly "output"?: string;
}

export interface FlowStartParameters {
}

export interface FlowStopParameters {
  readonly "output"?: string;
}

export interface FlowRunParameters {
  readonly "input": string;
}

export interface NetworkEmulateParameters {
  readonly "offline"?: boolean;
  readonly "latencyMs"?: number;
  readonly "downloadKbps"?: number;
  readonly "uploadKbps"?: number;
}

export interface NetworkMockSetParameters {
  readonly "url": string;
  readonly "status"?: number;
  readonly "body": string;
  readonly "contentType"?: string;
}

export interface NetworkMockClearParameters {
}

export interface AuthLoginParameters {
  readonly "challenge"?: string;
  readonly "account"?: string;
  readonly "interactive"?: boolean;
}

export interface HostStatus {
  readonly "ready": boolean;
  readonly "pid": number;
  readonly "engine": string;
  readonly "platform": string;
  readonly "productVersion": string;
  readonly "protocolVersion": string;
  readonly "capabilities": Readonly<Record<string, JsonValue>>;
  readonly "recordingAvailable": boolean;
  readonly "artifactDirectory": string;
  readonly "navigationAllowlist": readonly JsonValue[];
  readonly [key: string]: JsonValue;
}

export interface Shutdown {
  readonly "stopping": boolean;
  readonly [key: string]: JsonValue;
}

export interface ProfileClear {
  readonly "cleared": boolean;
  readonly "session": string;
  readonly [key: string]: JsonValue;
}

export interface SessionCreate {
  readonly "session": string;
  readonly "isolated": boolean;
  readonly [key: string]: JsonValue;
}

export interface SessionList {
  readonly "sessions": readonly JsonValue[];
  readonly "details": readonly JsonValue[];
  readonly [key: string]: JsonValue;
}

export interface SessionClose {
  readonly "closed": string;
  readonly [key: string]: JsonValue;
}

export interface PageState {
  readonly "url": string;
  readonly "title": string;
  readonly "readyState": string;
  readonly "text": string;
  readonly "runningAnimations": number;
  readonly "mutationQuietMs": number;
  readonly "scrollY": number;
  readonly "contentHeight": number;
  readonly [key: string]: JsonValue;
}

export interface Inspection {
  readonly "url": string;
  readonly "title": string;
  readonly "contextMode": string;
  readonly "viewport": Readonly<Record<string, JsonValue>>;
  readonly "untrustedContent": boolean;
  readonly "elements"?: readonly JsonValue[];
  readonly "regions"?: readonly JsonValue[];
  readonly "snippets"?: readonly JsonValue[];
  readonly "text"?: string;
  readonly [key: string]: JsonValue;
}

export interface Click {
  readonly "clicked": string;
  readonly "role": string;
  readonly "name": string;
  readonly [key: string]: JsonValue;
}

export interface Fill {
  readonly "filled": string;
  readonly "valueLength": number;
  readonly [key: string]: JsonValue;
}

export interface Upload {
  readonly "uploaded": string;
  readonly "role": string;
  readonly "name": string;
  readonly "artifact": string;
  readonly [key: string]: JsonValue;
}

export interface Press {
  readonly "pressed": string;
  readonly [key: string]: JsonValue;
}

export interface Scroll {
  readonly "direction": string;
  readonly "amount": number;
  readonly [key: string]: JsonValue;
}

export interface Tour {
  readonly "start": number;
  readonly "end": number;
  readonly "durationMs": number;
  readonly [key: string]: JsonValue;
}

export interface CaptureInfo {
  readonly "engine": string;
  readonly "page": Readonly<Record<string, JsonValue>>;
  readonly "trace": readonly JsonValue[];
  readonly "recording": Readonly<Record<string, JsonValue>>;
  readonly [key: string]: JsonValue;
}

export interface Screenshot {
  readonly "name"?: string;
  readonly "path"?: string;
  readonly "kind"?: string;
  readonly "bytes"?: number;
  readonly "createdAt"?: number;
  readonly "artifacts"?: readonly JsonValue[];
  readonly "truncated"?: boolean;
  readonly [key: string]: JsonValue;
}

export interface ArtifactList {
  readonly "directory": string;
  readonly "artifacts": readonly JsonValue[];
  readonly "total": number;
  readonly "omitted": number;
  readonly "truncated": boolean;
  readonly [key: string]: JsonValue;
}

export interface Recording {
  readonly "active": boolean;
  readonly "format"?: string;
  readonly "quality"?: string;
  readonly "name"?: string;
  readonly [key: string]: JsonValue;
}

export interface QAReport {
  readonly "untrustedContent": boolean;
  readonly "summary": Readonly<Record<string, JsonValue>>;
  readonly "issues": readonly JsonValue[];
  readonly "events": readonly JsonValue[];
  readonly "omitted": Readonly<Record<string, JsonValue>>;
  readonly "truncated": boolean;
  readonly [key: string]: JsonValue;
}

export interface QAClear {
  readonly "cleared": number;
  readonly [key: string]: JsonValue;
}

export interface ConsoleList {
  readonly "untrustedContent": boolean;
  readonly "messages": readonly JsonValue[];
  readonly "returned": number;
  readonly "available": number;
  readonly [key: string]: JsonValue;
}

export interface NetworkList {
  readonly "untrustedContent": boolean;
  readonly "requests": readonly JsonValue[];
  readonly "returned": number;
  readonly "available": number;
  readonly [key: string]: JsonValue;
}

export interface NetworkDetail {
  readonly "found": boolean;
  readonly "requestId"?: string;
  readonly "untrustedContent": boolean;
  readonly "request"?: Readonly<Record<string, JsonValue>>;
  readonly [key: string]: JsonValue;
}

export interface Styles {
  readonly "ref": string;
  readonly "role": string;
  readonly "name": string;
  readonly "box": Readonly<Record<string, JsonValue>>;
  readonly "styles": Readonly<Record<string, JsonValue>>;
  readonly [key: string]: JsonValue;
}

export interface CookieList {
  readonly "cookies": readonly JsonValue[];
  readonly "returned": number;
  readonly "available": number;
  readonly "truncated": boolean;
  readonly [key: string]: JsonValue;
}

export interface StorageList {
  readonly "origin": string;
  readonly "stores": readonly JsonValue[];
  readonly [key: string]: JsonValue;
}

export interface VisualComparison {
  readonly "name": string;
  readonly "changedPixels"?: number;
  readonly "differenceRatio"?: number;
  readonly [key: string]: JsonValue;
}

export interface Performance {
  readonly "url": string;
  readonly "timing": JsonValue;
  readonly "webVitals": Readonly<Record<string, JsonValue>>;
  readonly "resources": Readonly<Record<string, JsonValue>>;
  readonly [key: string]: JsonValue;
}

export interface AnimationList {
  readonly "count": number;
  readonly "animations": readonly JsonValue[];
  readonly "truncated": boolean;
  readonly [key: string]: JsonValue;
}

export interface Artifact {
  readonly "name": string;
  readonly "path": string;
  readonly "kind": string;
  readonly "bytes": number;
  readonly "createdAt": number;
  readonly [key: string]: JsonValue;
}

export interface FlowStart {
  readonly "recording": boolean;
  readonly "note": string;
  readonly [key: string]: JsonValue;
}

export interface FlowRun {
  readonly "completed": number;
  readonly "input": string;
  readonly [key: string]: JsonValue;
}

export interface NetworkEmulation {
  readonly "offline": boolean;
  readonly "latencyMs": number;
  readonly "downloadKbps": number;
  readonly "uploadKbps": number;
  readonly "engine": string;
  readonly [key: string]: JsonValue;
}

export interface NetworkMock {
  readonly "url": string;
  readonly "status": number;
  readonly "activeMocks": number;
  readonly [key: string]: JsonValue;
}

export interface NetworkMockClear {
  readonly "cleared": number;
  readonly [key: string]: JsonValue;
}

export interface AuthenticationLogin {
  readonly "origin": string;
  readonly "account": string | null;
  readonly "saved": boolean;
  readonly "continuation": string;
  readonly "passwordExposed": boolean;
  readonly "originalActionReplayed": boolean;
  readonly [key: string]: JsonValue;
}

export interface AuthenticationRequired {
  readonly "challenge": string;
  readonly "origin": string;
  readonly "detection": string;
  readonly "accounts": readonly JsonValue[];
  readonly "expiresInSeconds": number;
  readonly "userPresenceRequired": boolean;
  readonly "credentialUseAvailable": boolean;
  readonly "vaultAvailable": boolean;
  readonly "vaultStatus": string;
  readonly "untrustedContent": boolean;
  readonly "originalActionReplayed": boolean;
  readonly [key: string]: JsonValue;
}

export type CommandErrorCode = "ARTIFACT_ERROR" | "AUTH_ACCOUNT_NOT_FOUND" | "AUTH_CHALLENGE_CONSUMED" | "AUTH_CHALLENGE_EXPIRED" | "AUTH_CHALLENGE_NOT_FOUND" | "AUTH_FORM_CHANGED" | "AUTH_ORIGIN_CHANGED" | "AUTH_REQUIRED" | "CREDENTIAL_ALIAS_EXISTS" | "ELEMENT_NOT_FOUND" | "FLOW_FAILED" | "HOST_STOPPING" | "HOST_UNAVAILABLE" | "INTERNAL_ERROR" | "INVALID_CAPTURE_FORMAT" | "INVALID_COMMAND" | "INVALID_FLOW" | "INVALID_INPUT" | "INVALID_REQUEST" | "INVALID_SESSION" | "MISSING_PARAMETER" | "OPERATION_FAILED" | "PEER_DENIED" | "RECORDER_UNAVAILABLE" | "RECORDING_ACTIVE" | "RECORDING_FAILED" | "RECORDING_NOT_ACTIVE" | "REGION_NOT_FOUND" | "RESPONSE_TOO_LARGE" | "SENSITIVE_DIAGNOSTICS_DISABLED" | "SESSION_EXISTS" | "SESSION_NOT_FOUND" | "TIMEOUT" | "UNSAFE_NAVIGATION" | "UNSAFE_RESOURCE_TYPE" | "UNSUPPORTED_CAPABILITY" | "USER_PRESENCE_DENIED" | "USER_PRESENCE_UNAVAILABLE" | "VAULT_LOCKED" | "VAULT_OPERATION_FAILED" | "VAULT_RESPONSE_INVALID" | "VAULT_UNAVAILABLE";

export type LifecycleErrorCode = "HOST_START_FAILED" | "NAVIGATION_ALLOWLIST_CONFLICT" | "UNSUPPORTED_BROWSER_RUNTIME" | "UNSUPPORTED_CAPABILITY";

export const LIFECYCLE_ERROR_CODES = ["HOST_START_FAILED","NAVIGATION_ALLOWLIST_CONFLICT","UNSUPPORTED_BROWSER_RUNTIME","UNSUPPORTED_CAPABILITY"] as const;

export interface ErrorDetails {
  readonly "AUTH_REQUIRED": Untrusted<AuthenticationRequired>;
}

export const ERROR_DETAILS_METADATA = {
  "AUTH_REQUIRED": {
    "mayContainUntrustedContent": true,
    "schema": {
      "additionalProperties": true,
      "fields": [
        {
          "name": "challenge",
          "required": true,
          "type": "string"
        },
        {
          "name": "origin",
          "required": true,
          "type": "string"
        },
        {
          "name": "detection",
          "required": true,
          "type": "string"
        },
        {
          "name": "accounts",
          "required": true,
          "type": "array"
        },
        {
          "name": "expiresInSeconds",
          "required": true,
          "type": "number"
        },
        {
          "name": "userPresenceRequired",
          "required": true,
          "type": "boolean"
        },
        {
          "name": "credentialUseAvailable",
          "required": true,
          "type": "boolean"
        },
        {
          "name": "vaultAvailable",
          "required": true,
          "type": "boolean"
        },
        {
          "name": "vaultStatus",
          "required": true,
          "type": "string"
        },
        {
          "name": "untrustedContent",
          "required": true,
          "type": "boolean"
        },
        {
          "name": "originalActionReplayed",
          "required": true,
          "type": "boolean"
        }
      ],
      "name": "AuthenticationRequired",
      "type": "object"
    }
  }
} as const;

export type CommandName = "ping" | "shutdown" | "profile.clear" | "session.create" | "session.list" | "session.close" | "visit" | "inspect" | "click" | "fill" | "upload" | "press" | "scroll" | "back" | "reload" | "wait" | "tour" | "capture.info" | "screenshot" | "artifact.list" | "record.start" | "record.status" | "record.stop" | "qa.report" | "qa.clear" | "console.list" | "network.list" | "network.get" | "styles.get" | "cookies.list" | "storage.list" | "visual.compare" | "performance.get" | "animation.list" | "report.create" | "flow.start" | "flow.stop" | "flow.run" | "network.emulate" | "network.mock.set" | "network.mock.clear" | "auth.login";

export interface CommandParameters {
  readonly "ping": PingParameters;
  readonly "shutdown": ShutdownParameters;
  readonly "profile.clear": ProfileClearParameters;
  readonly "session.create": SessionCreateParameters;
  readonly "session.list": SessionListParameters;
  readonly "session.close": SessionCloseParameters;
  readonly "visit": VisitParameters;
  readonly "inspect": InspectParameters;
  readonly "click": ClickParameters;
  readonly "fill": FillParameters;
  readonly "upload": UploadParameters;
  readonly "press": PressParameters;
  readonly "scroll": ScrollParameters;
  readonly "back": BackParameters;
  readonly "reload": ReloadParameters;
  readonly "wait": WaitParameters;
  readonly "tour": TourParameters;
  readonly "capture.info": CaptureInfoParameters;
  readonly "screenshot": ScreenshotParameters;
  readonly "artifact.list": ArtifactListParameters;
  readonly "record.start": RecordStartParameters;
  readonly "record.status": RecordStatusParameters;
  readonly "record.stop": RecordStopParameters;
  readonly "qa.report": QaReportParameters;
  readonly "qa.clear": QaClearParameters;
  readonly "console.list": ConsoleListParameters;
  readonly "network.list": NetworkListParameters;
  readonly "network.get": NetworkGetParameters;
  readonly "styles.get": StylesGetParameters;
  readonly "cookies.list": CookiesListParameters;
  readonly "storage.list": StorageListParameters;
  readonly "visual.compare": VisualCompareParameters;
  readonly "performance.get": PerformanceGetParameters;
  readonly "animation.list": AnimationListParameters;
  readonly "report.create": ReportCreateParameters;
  readonly "flow.start": FlowStartParameters;
  readonly "flow.stop": FlowStopParameters;
  readonly "flow.run": FlowRunParameters;
  readonly "network.emulate": NetworkEmulateParameters;
  readonly "network.mock.set": NetworkMockSetParameters;
  readonly "network.mock.clear": NetworkMockClearParameters;
  readonly "auth.login": AuthLoginParameters;
}

export interface CommandResults {
  readonly "ping": HostStatus;
  readonly "shutdown": Shutdown;
  readonly "profile.clear": ProfileClear;
  readonly "session.create": SessionCreate;
  readonly "session.list": SessionList;
  readonly "session.close": SessionClose;
  readonly "visit": Untrusted<PageState>;
  readonly "inspect": Untrusted<Inspection>;
  readonly "click": Untrusted<Click>;
  readonly "fill": Untrusted<Fill>;
  readonly "upload": Untrusted<Upload>;
  readonly "press": Untrusted<Press>;
  readonly "scroll": Untrusted<Scroll>;
  readonly "back": Untrusted<PageState>;
  readonly "reload": Untrusted<PageState>;
  readonly "wait": Untrusted<PageState>;
  readonly "tour": Untrusted<Tour>;
  readonly "capture.info": Untrusted<CaptureInfo>;
  readonly "screenshot": Screenshot;
  readonly "artifact.list": ArtifactList;
  readonly "record.start": Recording;
  readonly "record.status": Recording;
  readonly "record.stop": Recording;
  readonly "qa.report": Untrusted<QAReport>;
  readonly "qa.clear": QAClear;
  readonly "console.list": Untrusted<ConsoleList>;
  readonly "network.list": Untrusted<NetworkList>;
  readonly "network.get": Untrusted<NetworkDetail>;
  readonly "styles.get": Untrusted<Styles>;
  readonly "cookies.list": Untrusted<CookieList>;
  readonly "storage.list": Untrusted<StorageList>;
  readonly "visual.compare": VisualComparison;
  readonly "performance.get": Untrusted<Performance>;
  readonly "animation.list": Untrusted<AnimationList>;
  readonly "report.create": Untrusted<Artifact>;
  readonly "flow.start": FlowStart;
  readonly "flow.stop": Artifact;
  readonly "flow.run": Untrusted<FlowRun>;
  readonly "network.emulate": NetworkEmulation;
  readonly "network.mock.set": Untrusted<NetworkMock>;
  readonly "network.mock.clear": NetworkMockClear;
  readonly "auth.login": Untrusted<AuthenticationLogin>;
}

export type CommandResult<C extends CommandName> = CommandResults[C];

export const COMMAND_METADATA = {
  "ping": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "ready",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "pid",
            "required": true,
            "type": "number"
          },
          {
            "name": "engine",
            "required": true,
            "type": "string"
          },
          {
            "name": "platform",
            "required": true,
            "type": "string"
          },
          {
            "name": "productVersion",
            "required": true,
            "type": "string"
          },
          {
            "name": "protocolVersion",
            "required": true,
            "type": "string"
          },
          {
            "name": "capabilities",
            "required": true,
            "type": "object"
          },
          {
            "name": "recordingAvailable",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "artifactDirectory",
            "required": true,
            "type": "string"
          },
          {
            "name": "navigationAllowlist",
            "required": true,
            "type": "array"
          }
        ],
        "name": "HostStatus",
        "type": "object"
      }
    },
    "scope": "host",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "shutdown": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "stopping",
            "required": true,
            "type": "boolean"
          }
        ],
        "name": "Shutdown",
        "type": "object"
      }
    },
    "scope": "host",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "profile.clear": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "cleared",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "session",
            "required": true,
            "type": "string"
          }
        ],
        "name": "ProfileClear",
        "type": "object"
      }
    },
    "scope": "host",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "session.create": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 64,
        "name": "name",
        "required": true,
        "sensitive": false,
        "type": "string"
      },
      {
        "name": "isolated",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      }
    ],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "session",
            "required": true,
            "type": "string"
          },
          {
            "name": "isolated",
            "required": true,
            "type": "boolean"
          }
        ],
        "name": "SessionCreate",
        "type": "object"
      }
    },
    "scope": "host",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "session.list": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "sessions",
            "required": true,
            "type": "array"
          },
          {
            "name": "details",
            "required": true,
            "type": "array"
          }
        ],
        "name": "SessionList",
        "type": "object"
      }
    },
    "scope": "host",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "session.close": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "closed",
            "required": true,
            "type": "string"
          }
        ],
        "name": "SessionClose",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "visit": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 8192,
        "name": "url",
        "required": true,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "url",
            "required": true,
            "type": "string"
          },
          {
            "name": "title",
            "required": true,
            "type": "string"
          },
          {
            "name": "readyState",
            "required": true,
            "type": "string"
          },
          {
            "name": "text",
            "required": true,
            "type": "string"
          },
          {
            "name": "runningAnimations",
            "required": true,
            "type": "number"
          },
          {
            "name": "mutationQuietMs",
            "required": true,
            "type": "number"
          },
          {
            "name": "scrollY",
            "required": true,
            "type": "number"
          },
          {
            "name": "contentHeight",
            "required": true,
            "type": "number"
          }
        ],
        "name": "PageState",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "inspect": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "name": "interactive",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      },
      {
        "name": "text",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      },
      {
        "maximumBytes": 16,
        "name": "context",
        "required": false,
        "sensitive": false,
        "type": "string",
        "values": [
          "summary",
          "outline",
          "text",
          "actions",
          "full"
        ]
      },
      {
        "maximumBytes": 512,
        "name": "task",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 16,
        "name": "within",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximum": 250,
        "minimum": 1,
        "name": "limit",
        "required": false,
        "sensitive": false,
        "type": "integer"
      },
      {
        "maximum": 16000,
        "minimum": 256,
        "name": "budget",
        "required": false,
        "sensitive": false,
        "type": "integer"
      },
      {
        "maximum": 8,
        "minimum": 0,
        "name": "depth",
        "required": false,
        "sensitive": false,
        "type": "integer"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "url",
            "required": true,
            "type": "string"
          },
          {
            "name": "title",
            "required": true,
            "type": "string"
          },
          {
            "name": "contextMode",
            "required": true,
            "type": "string"
          },
          {
            "name": "viewport",
            "required": true,
            "type": "object"
          },
          {
            "name": "untrustedContent",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "elements",
            "required": false,
            "type": "array"
          },
          {
            "name": "regions",
            "required": false,
            "type": "array"
          },
          {
            "name": "snippets",
            "required": false,
            "type": "array"
          },
          {
            "name": "text",
            "required": false,
            "type": "string"
          }
        ],
        "name": "Inspection",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "click": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 16,
        "name": "target",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 128,
        "name": "role",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 1000,
        "name": "name",
        "required": false,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "clicked",
            "required": true,
            "type": "string"
          },
          {
            "name": "role",
            "required": true,
            "type": "string"
          },
          {
            "name": "name",
            "required": true,
            "type": "string"
          }
        ],
        "name": "Click",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "fill": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 16,
        "name": "target",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 128,
        "name": "role",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 1000,
        "name": "name",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 900000,
        "name": "value",
        "required": true,
        "sensitive": true,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "filled",
            "required": true,
            "type": "string"
          },
          {
            "name": "valueLength",
            "required": true,
            "type": "number"
          }
        ],
        "name": "Fill",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "upload": {
    "capabilityNegotiated": true,
    "parameters": [
      {
        "maximumBytes": 16,
        "name": "target",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 128,
        "name": "role",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 1000,
        "name": "name",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 128,
        "name": "artifact",
        "required": true,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "uploaded",
            "required": true,
            "type": "string"
          },
          {
            "name": "role",
            "required": true,
            "type": "string"
          },
          {
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "name": "artifact",
            "required": true,
            "type": "string"
          }
        ],
        "name": "Upload",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "press": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 32,
        "name": "key",
        "required": true,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "pressed",
            "required": true,
            "type": "string"
          }
        ],
        "name": "Press",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "scroll": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 8192,
        "name": "direction",
        "required": false,
        "sensitive": false,
        "type": "string",
        "values": [
          "up",
          "down",
          "top",
          "bottom"
        ]
      },
      {
        "maximum": 100000,
        "minimum": 0.1,
        "name": "amount",
        "required": false,
        "sensitive": false,
        "type": "number"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "direction",
            "required": true,
            "type": "string"
          },
          {
            "name": "amount",
            "required": true,
            "type": "number"
          }
        ],
        "name": "Scroll",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "back": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "url",
            "required": true,
            "type": "string"
          },
          {
            "name": "title",
            "required": true,
            "type": "string"
          },
          {
            "name": "readyState",
            "required": true,
            "type": "string"
          },
          {
            "name": "text",
            "required": true,
            "type": "string"
          },
          {
            "name": "runningAnimations",
            "required": true,
            "type": "number"
          },
          {
            "name": "mutationQuietMs",
            "required": true,
            "type": "number"
          },
          {
            "name": "scrollY",
            "required": true,
            "type": "number"
          },
          {
            "name": "contentHeight",
            "required": true,
            "type": "number"
          }
        ],
        "name": "PageState",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "reload": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "url",
            "required": true,
            "type": "string"
          },
          {
            "name": "title",
            "required": true,
            "type": "string"
          },
          {
            "name": "readyState",
            "required": true,
            "type": "string"
          },
          {
            "name": "text",
            "required": true,
            "type": "string"
          },
          {
            "name": "runningAnimations",
            "required": true,
            "type": "number"
          },
          {
            "name": "mutationQuietMs",
            "required": true,
            "type": "number"
          },
          {
            "name": "scrollY",
            "required": true,
            "type": "number"
          },
          {
            "name": "contentHeight",
            "required": true,
            "type": "number"
          }
        ],
        "name": "PageState",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "wait": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "name": "settled",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      },
      {
        "maximumBytes": 8192,
        "name": "url",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 30000,
        "name": "text",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximum": 120000,
        "minimum": 100,
        "name": "timeoutMs",
        "required": false,
        "sensitive": false,
        "type": "number"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "url",
            "required": true,
            "type": "string"
          },
          {
            "name": "title",
            "required": true,
            "type": "string"
          },
          {
            "name": "readyState",
            "required": true,
            "type": "string"
          },
          {
            "name": "text",
            "required": true,
            "type": "string"
          },
          {
            "name": "runningAnimations",
            "required": true,
            "type": "number"
          },
          {
            "name": "mutationQuietMs",
            "required": true,
            "type": "number"
          },
          {
            "name": "scrollY",
            "required": true,
            "type": "number"
          },
          {
            "name": "contentHeight",
            "required": true,
            "type": "number"
          }
        ],
        "name": "PageState",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "maximumMilliseconds": 125000,
      "minimumMilliseconds": 10000,
      "parameterGraceMilliseconds": 5000,
      "parameterName": "timeoutMs",
      "parameterPresentOverrides": {}
    }
  },
  "tour": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "name": "fullPage",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      },
      {
        "maximum": 5000,
        "minimum": 100,
        "name": "pace",
        "required": false,
        "sensitive": false,
        "type": "number"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "start",
            "required": true,
            "type": "number"
          },
          {
            "name": "end",
            "required": true,
            "type": "number"
          },
          {
            "name": "durationMs",
            "required": true,
            "type": "number"
          }
        ],
        "name": "Tour",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 125000,
      "parameterPresentOverrides": {}
    }
  },
  "capture.info": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "engine",
            "required": true,
            "type": "string"
          },
          {
            "name": "page",
            "required": true,
            "type": "object"
          },
          {
            "name": "trace",
            "required": true,
            "type": "array"
          },
          {
            "name": "recording",
            "required": true,
            "type": "object"
          }
        ],
        "name": "CaptureInfo",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "screenshot": {
    "capabilityNegotiated": true,
    "parameters": [
      {
        "maximumBytes": 16,
        "name": "target",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 128,
        "name": "role",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 1000,
        "name": "name",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "name": "fullPage",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      },
      {
        "maximumBytes": 128,
        "name": "output",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 32,
        "name": "series",
        "required": false,
        "sensitive": false,
        "type": "string",
        "values": [
          "viewport",
          "section"
        ]
      },
      {
        "maximumBytes": 80,
        "name": "outputPrefix",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "caseInsensitiveValues": true,
        "maximumBytes": 16,
        "name": "format",
        "required": false,
        "sensitive": false,
        "type": "string",
        "values": [
          "png",
          "jpg",
          "jpeg",
          "pdf"
        ]
      },
      {
        "name": "clipboard",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      }
    ],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "name",
            "required": false,
            "type": "string"
          },
          {
            "name": "path",
            "required": false,
            "type": "string"
          },
          {
            "name": "kind",
            "required": false,
            "type": "string"
          },
          {
            "name": "bytes",
            "required": false,
            "type": "number"
          },
          {
            "name": "createdAt",
            "required": false,
            "type": "number"
          },
          {
            "name": "artifacts",
            "required": false,
            "type": "array"
          },
          {
            "name": "truncated",
            "required": false,
            "type": "boolean"
          }
        ],
        "name": "Screenshot",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 30000,
      "parameterPresentOverrides": {
        "series": 125000
      }
    }
  },
  "artifact.list": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "directory",
            "required": true,
            "type": "string"
          },
          {
            "name": "artifacts",
            "required": true,
            "type": "array"
          },
          {
            "name": "total",
            "required": true,
            "type": "number"
          },
          {
            "name": "omitted",
            "required": true,
            "type": "number"
          },
          {
            "name": "truncated",
            "required": true,
            "type": "boolean"
          }
        ],
        "name": "ArtifactList",
        "type": "object"
      }
    },
    "scope": "host",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "record.start": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 128,
        "name": "output",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximum": 30,
        "minimum": 1,
        "name": "fps",
        "required": false,
        "sensitive": false,
        "type": "number"
      },
      {
        "caseInsensitiveValues": true,
        "maximumBytes": 16,
        "name": "format",
        "required": false,
        "sensitive": false,
        "type": "string",
        "values": [
          "mp4",
          "mov",
          "webm",
          "gif"
        ]
      },
      {
        "caseInsensitiveValues": true,
        "maximumBytes": 16,
        "name": "quality",
        "required": false,
        "sensitive": false,
        "type": "string",
        "values": [
          "fast",
          "balanced",
          "high"
        ]
      }
    ],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "active",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "format",
            "required": false,
            "type": "string"
          },
          {
            "name": "quality",
            "required": false,
            "type": "string"
          },
          {
            "name": "name",
            "required": false,
            "type": "string"
          }
        ],
        "name": "Recording",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "record.status": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "active",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "format",
            "required": false,
            "type": "string"
          },
          {
            "name": "quality",
            "required": false,
            "type": "string"
          },
          {
            "name": "name",
            "required": false,
            "type": "string"
          }
        ],
        "name": "Recording",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "record.stop": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 128,
        "name": "output",
        "required": false,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "active",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "format",
            "required": false,
            "type": "string"
          },
          {
            "name": "quality",
            "required": false,
            "type": "string"
          },
          {
            "name": "name",
            "required": false,
            "type": "string"
          }
        ],
        "name": "Recording",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 30000,
      "parameterPresentOverrides": {}
    }
  },
  "qa.report": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "untrustedContent",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "summary",
            "required": true,
            "type": "object"
          },
          {
            "name": "issues",
            "required": true,
            "type": "array"
          },
          {
            "name": "events",
            "required": true,
            "type": "array"
          },
          {
            "name": "omitted",
            "required": true,
            "type": "object"
          },
          {
            "name": "truncated",
            "required": true,
            "type": "boolean"
          }
        ],
        "name": "QAReport",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "qa.clear": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "cleared",
            "required": true,
            "type": "number"
          }
        ],
        "name": "QAClear",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "console.list": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 16,
        "name": "level",
        "required": false,
        "sensitive": false,
        "type": "string",
        "values": [
          "all",
          "log",
          "info",
          "debug",
          "warn",
          "error",
          "assert"
        ]
      },
      {
        "maximum": 200,
        "minimum": 1,
        "name": "limit",
        "required": false,
        "sensitive": false,
        "type": "number"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "untrustedContent",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "messages",
            "required": true,
            "type": "array"
          },
          {
            "name": "returned",
            "required": true,
            "type": "number"
          },
          {
            "name": "available",
            "required": true,
            "type": "number"
          }
        ],
        "name": "ConsoleList",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "network.list": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "name": "failed",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      },
      {
        "maximum": 599,
        "minimum": 100,
        "name": "status",
        "required": false,
        "sensitive": false,
        "type": "number"
      },
      {
        "maximum": 200,
        "minimum": 1,
        "name": "limit",
        "required": false,
        "sensitive": false,
        "type": "number"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "untrustedContent",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "requests",
            "required": true,
            "type": "array"
          },
          {
            "name": "returned",
            "required": true,
            "type": "number"
          },
          {
            "name": "available",
            "required": true,
            "type": "number"
          }
        ],
        "name": "NetworkList",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "network.get": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 128,
        "name": "requestId",
        "required": true,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "found",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "requestId",
            "required": false,
            "type": "string"
          },
          {
            "name": "untrustedContent",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "request",
            "required": false,
            "type": "object"
          }
        ],
        "name": "NetworkDetail",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "styles.get": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 16,
        "name": "target",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 128,
        "name": "role",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 1000,
        "name": "name",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "itemMaximumBytes": 128,
        "maximumItems": 64,
        "name": "properties",
        "required": false,
        "sensitive": false,
        "type": "string-array"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "ref",
            "required": true,
            "type": "string"
          },
          {
            "name": "role",
            "required": true,
            "type": "string"
          },
          {
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "name": "box",
            "required": true,
            "type": "object"
          },
          {
            "name": "styles",
            "required": true,
            "type": "object"
          }
        ],
        "name": "Styles",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "cookies.list": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "name": "includeValues",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "cookies",
            "required": true,
            "type": "array"
          },
          {
            "name": "returned",
            "required": true,
            "type": "number"
          },
          {
            "name": "available",
            "required": true,
            "type": "number"
          },
          {
            "name": "truncated",
            "required": true,
            "type": "boolean"
          }
        ],
        "name": "CookieList",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "storage.list": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 16,
        "name": "scope",
        "required": false,
        "sensitive": false,
        "type": "string",
        "values": [
          "local",
          "session",
          "all"
        ]
      },
      {
        "name": "includeValues",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "origin",
            "required": true,
            "type": "string"
          },
          {
            "name": "stores",
            "required": true,
            "type": "array"
          }
        ],
        "name": "StorageList",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "visual.compare": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 128,
        "name": "before",
        "required": true,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 128,
        "name": "after",
        "required": true,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 128,
        "name": "output",
        "required": false,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "name": "changedPixels",
            "required": false,
            "type": "number"
          },
          {
            "name": "differenceRatio",
            "required": false,
            "type": "number"
          }
        ],
        "name": "VisualComparison",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "performance.get": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "url",
            "required": true,
            "type": "string"
          },
          {
            "name": "timing",
            "required": true,
            "type": "json"
          },
          {
            "name": "webVitals",
            "required": true,
            "type": "object"
          },
          {
            "name": "resources",
            "required": true,
            "type": "object"
          }
        ],
        "name": "Performance",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "animation.list": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "count",
            "required": true,
            "type": "number"
          },
          {
            "name": "animations",
            "required": true,
            "type": "array"
          },
          {
            "name": "truncated",
            "required": true,
            "type": "boolean"
          }
        ],
        "name": "AnimationList",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "report.create": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 128,
        "name": "output",
        "required": false,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "name": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "kind",
            "required": true,
            "type": "string"
          },
          {
            "name": "bytes",
            "required": true,
            "type": "number"
          },
          {
            "name": "createdAt",
            "required": true,
            "type": "number"
          }
        ],
        "name": "Artifact",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "flow.start": {
    "capabilityNegotiated": false,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "recording",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "note",
            "required": true,
            "type": "string"
          }
        ],
        "name": "FlowStart",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "flow.stop": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 128,
        "name": "output",
        "required": false,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "name": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "kind",
            "required": true,
            "type": "string"
          },
          {
            "name": "bytes",
            "required": true,
            "type": "number"
          },
          {
            "name": "createdAt",
            "required": true,
            "type": "number"
          }
        ],
        "name": "Artifact",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "flow.run": {
    "capabilityNegotiated": false,
    "parameters": [
      {
        "maximumBytes": 128,
        "name": "input",
        "required": true,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "completed",
            "required": true,
            "type": "number"
          },
          {
            "name": "input",
            "required": true,
            "type": "string"
          }
        ],
        "name": "FlowRun",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 125000,
      "parameterPresentOverrides": {}
    }
  },
  "network.emulate": {
    "capabilityNegotiated": true,
    "parameters": [
      {
        "name": "offline",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      },
      {
        "maximum": 120000,
        "minimum": 0,
        "name": "latencyMs",
        "required": false,
        "sensitive": false,
        "type": "number"
      },
      {
        "maximum": 1000000,
        "minimum": -1,
        "name": "downloadKbps",
        "required": false,
        "sensitive": false,
        "type": "number"
      },
      {
        "maximum": 1000000,
        "minimum": -1,
        "name": "uploadKbps",
        "required": false,
        "sensitive": false,
        "type": "number"
      }
    ],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "offline",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "latencyMs",
            "required": true,
            "type": "number"
          },
          {
            "name": "downloadKbps",
            "required": true,
            "type": "number"
          },
          {
            "name": "uploadKbps",
            "required": true,
            "type": "number"
          },
          {
            "name": "engine",
            "required": true,
            "type": "string"
          }
        ],
        "name": "NetworkEmulation",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "network.mock.set": {
    "capabilityNegotiated": true,
    "parameters": [
      {
        "maximumBytes": 8192,
        "name": "url",
        "required": true,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximum": 599,
        "minimum": 100,
        "name": "status",
        "required": false,
        "sensitive": false,
        "type": "number"
      },
      {
        "maximumBytes": 65536,
        "name": "body",
        "required": true,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 256,
        "name": "contentType",
        "required": false,
        "sensitive": false,
        "type": "string"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "url",
            "required": true,
            "type": "string"
          },
          {
            "name": "status",
            "required": true,
            "type": "number"
          },
          {
            "name": "activeMocks",
            "required": true,
            "type": "number"
          }
        ],
        "name": "NetworkMock",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "network.mock.clear": {
    "capabilityNegotiated": true,
    "parameters": [],
    "result": {
      "mayContainUntrustedContent": false,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "cleared",
            "required": true,
            "type": "number"
          }
        ],
        "name": "NetworkMockClear",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  },
  "auth.login": {
    "capabilityNegotiated": true,
    "parameters": [
      {
        "maximumBytes": 64,
        "name": "challenge",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "maximumBytes": 64,
        "name": "account",
        "required": false,
        "sensitive": false,
        "type": "string"
      },
      {
        "name": "interactive",
        "required": false,
        "sensitive": false,
        "type": "boolean"
      }
    ],
    "result": {
      "mayContainUntrustedContent": true,
      "schema": {
        "additionalProperties": true,
        "fields": [
          {
            "name": "origin",
            "required": true,
            "type": "string"
          },
          {
            "name": "account",
            "required": true,
            "type": "string-or-null"
          },
          {
            "name": "saved",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "continuation",
            "required": true,
            "type": "string"
          },
          {
            "name": "passwordExposed",
            "required": true,
            "type": "boolean"
          },
          {
            "name": "originalActionReplayed",
            "required": true,
            "type": "boolean"
          }
        ],
        "name": "AuthenticationLogin",
        "type": "object"
      }
    },
    "scope": "session",
    "timeout": {
      "defaultMilliseconds": 15000,
      "parameterPresentOverrides": {}
    }
  }
} as const;

export function commandTimeoutMilliseconds<C extends CommandName>(
  command: C,
  parameters: CommandParameters[C],
): number {
  const policy = COMMAND_METADATA[command].timeout;
  for (const [parameter, timeout] of Object.entries(policy.parameterPresentOverrides)) {
    if ((parameters as Readonly<Record<string, unknown>>)[parameter] !== undefined) return timeout;
  }
  if ("parameterName" in policy) {
    const value = (parameters as Readonly<Record<string, unknown>>)[policy.parameterName];
    if (typeof value === "number") {
      return Math.max(
        policy.minimumMilliseconds,
        Math.min(policy.maximumMilliseconds, value + policy.parameterGraceMilliseconds),
      );
    }
  }
  return policy.defaultMilliseconds;
}

export abstract class GeneratedCommandClient {
  protected abstract invoke<C extends CommandName>(
    command: C,
    parameters: CommandParameters[C],
    options?: CommandOptions,
  ): Promise<CommandResult<C>>;

  ping(options?: CommandOptions): Promise<CommandResult<"ping">> {
    return this.invoke("ping", {}, options);
  }

  shutdown(options?: CommandOptions): Promise<CommandResult<"shutdown">> {
    return this.invoke("shutdown", {}, options);
  }

  profileClear(options?: CommandOptions): Promise<CommandResult<"profile.clear">> {
    return this.invoke("profile.clear", {}, options);
  }

  sessionCreate(parameters: SessionCreateParameters, options?: CommandOptions): Promise<CommandResult<"session.create">> {
    return this.invoke("session.create", parameters, options);
  }

  sessionList(options?: CommandOptions): Promise<CommandResult<"session.list">> {
    return this.invoke("session.list", {}, options);
  }

  sessionClose(options?: CommandOptions): Promise<CommandResult<"session.close">> {
    return this.invoke("session.close", {}, options);
  }

  visit(parameters: VisitParameters, options?: CommandOptions): Promise<CommandResult<"visit">> {
    return this.invoke("visit", parameters, options);
  }

  inspect(parameters: InspectParameters = {}, options?: CommandOptions): Promise<CommandResult<"inspect">> {
    return this.invoke("inspect", parameters, options);
  }

  click(parameters: ClickParameters = {}, options?: CommandOptions): Promise<CommandResult<"click">> {
    return this.invoke("click", parameters, options);
  }

  fill(parameters: FillParameters, options?: CommandOptions): Promise<CommandResult<"fill">> {
    return this.invoke("fill", parameters, options);
  }

  upload(parameters: UploadParameters, options?: CommandOptions): Promise<CommandResult<"upload">> {
    return this.invoke("upload", parameters, options);
  }

  press(parameters: PressParameters, options?: CommandOptions): Promise<CommandResult<"press">> {
    return this.invoke("press", parameters, options);
  }

  scroll(parameters: ScrollParameters = {}, options?: CommandOptions): Promise<CommandResult<"scroll">> {
    return this.invoke("scroll", parameters, options);
  }

  back(options?: CommandOptions): Promise<CommandResult<"back">> {
    return this.invoke("back", {}, options);
  }

  reload(options?: CommandOptions): Promise<CommandResult<"reload">> {
    return this.invoke("reload", {}, options);
  }

  wait(parameters: WaitParameters = {}, options?: CommandOptions): Promise<CommandResult<"wait">> {
    return this.invoke("wait", parameters, options);
  }

  tour(parameters: TourParameters = {}, options?: CommandOptions): Promise<CommandResult<"tour">> {
    return this.invoke("tour", parameters, options);
  }

  captureInfo(options?: CommandOptions): Promise<CommandResult<"capture.info">> {
    return this.invoke("capture.info", {}, options);
  }

  screenshot(parameters: ScreenshotParameters = {}, options?: CommandOptions): Promise<CommandResult<"screenshot">> {
    return this.invoke("screenshot", parameters, options);
  }

  artifactList(options?: CommandOptions): Promise<CommandResult<"artifact.list">> {
    return this.invoke("artifact.list", {}, options);
  }

  recordStart(parameters: RecordStartParameters = {}, options?: CommandOptions): Promise<CommandResult<"record.start">> {
    return this.invoke("record.start", parameters, options);
  }

  recordStatus(options?: CommandOptions): Promise<CommandResult<"record.status">> {
    return this.invoke("record.status", {}, options);
  }

  recordStop(parameters: RecordStopParameters = {}, options?: CommandOptions): Promise<CommandResult<"record.stop">> {
    return this.invoke("record.stop", parameters, options);
  }

  qaReport(options?: CommandOptions): Promise<CommandResult<"qa.report">> {
    return this.invoke("qa.report", {}, options);
  }

  qaClear(options?: CommandOptions): Promise<CommandResult<"qa.clear">> {
    return this.invoke("qa.clear", {}, options);
  }

  consoleList(parameters: ConsoleListParameters = {}, options?: CommandOptions): Promise<CommandResult<"console.list">> {
    return this.invoke("console.list", parameters, options);
  }

  networkList(parameters: NetworkListParameters = {}, options?: CommandOptions): Promise<CommandResult<"network.list">> {
    return this.invoke("network.list", parameters, options);
  }

  networkGet(parameters: NetworkGetParameters, options?: CommandOptions): Promise<CommandResult<"network.get">> {
    return this.invoke("network.get", parameters, options);
  }

  stylesGet(parameters: StylesGetParameters = {}, options?: CommandOptions): Promise<CommandResult<"styles.get">> {
    return this.invoke("styles.get", parameters, options);
  }

  cookiesList(parameters: CookiesListParameters = {}, options?: CommandOptions): Promise<CommandResult<"cookies.list">> {
    return this.invoke("cookies.list", parameters, options);
  }

  storageList(parameters: StorageListParameters = {}, options?: CommandOptions): Promise<CommandResult<"storage.list">> {
    return this.invoke("storage.list", parameters, options);
  }

  visualCompare(parameters: VisualCompareParameters, options?: CommandOptions): Promise<CommandResult<"visual.compare">> {
    return this.invoke("visual.compare", parameters, options);
  }

  performanceGet(options?: CommandOptions): Promise<CommandResult<"performance.get">> {
    return this.invoke("performance.get", {}, options);
  }

  animationList(options?: CommandOptions): Promise<CommandResult<"animation.list">> {
    return this.invoke("animation.list", {}, options);
  }

  reportCreate(parameters: ReportCreateParameters = {}, options?: CommandOptions): Promise<CommandResult<"report.create">> {
    return this.invoke("report.create", parameters, options);
  }

  flowStart(options?: CommandOptions): Promise<CommandResult<"flow.start">> {
    return this.invoke("flow.start", {}, options);
  }

  flowStop(parameters: FlowStopParameters = {}, options?: CommandOptions): Promise<CommandResult<"flow.stop">> {
    return this.invoke("flow.stop", parameters, options);
  }

  flowRun(parameters: FlowRunParameters, options?: CommandOptions): Promise<CommandResult<"flow.run">> {
    return this.invoke("flow.run", parameters, options);
  }

  networkEmulate(parameters: NetworkEmulateParameters = {}, options?: CommandOptions): Promise<CommandResult<"network.emulate">> {
    return this.invoke("network.emulate", parameters, options);
  }

  networkMockSet(parameters: NetworkMockSetParameters, options?: CommandOptions): Promise<CommandResult<"network.mock.set">> {
    return this.invoke("network.mock.set", parameters, options);
  }

  networkMockClear(options?: CommandOptions): Promise<CommandResult<"network.mock.clear">> {
    return this.invoke("network.mock.clear", {}, options);
  }

  authLogin(parameters: AuthLoginParameters = {}, options?: CommandOptions): Promise<CommandResult<"auth.login">> {
    return this.invoke("auth.login", parameters, options);
  }

}

export abstract class GeneratedSessionCommandClient {
  protected abstract invoke<C extends CommandName>(
    command: C,
    parameters: CommandParameters[C],
    options?: CommandOptions,
  ): Promise<CommandResult<C>>;

  sessionClose(options?: CommandOptions): Promise<CommandResult<"session.close">> {
    return this.invoke("session.close", {}, options);
  }

  visit(parameters: VisitParameters, options?: CommandOptions): Promise<CommandResult<"visit">> {
    return this.invoke("visit", parameters, options);
  }

  inspect(parameters: InspectParameters = {}, options?: CommandOptions): Promise<CommandResult<"inspect">> {
    return this.invoke("inspect", parameters, options);
  }

  click(parameters: ClickParameters = {}, options?: CommandOptions): Promise<CommandResult<"click">> {
    return this.invoke("click", parameters, options);
  }

  fill(parameters: FillParameters, options?: CommandOptions): Promise<CommandResult<"fill">> {
    return this.invoke("fill", parameters, options);
  }

  upload(parameters: UploadParameters, options?: CommandOptions): Promise<CommandResult<"upload">> {
    return this.invoke("upload", parameters, options);
  }

  press(parameters: PressParameters, options?: CommandOptions): Promise<CommandResult<"press">> {
    return this.invoke("press", parameters, options);
  }

  scroll(parameters: ScrollParameters = {}, options?: CommandOptions): Promise<CommandResult<"scroll">> {
    return this.invoke("scroll", parameters, options);
  }

  back(options?: CommandOptions): Promise<CommandResult<"back">> {
    return this.invoke("back", {}, options);
  }

  reload(options?: CommandOptions): Promise<CommandResult<"reload">> {
    return this.invoke("reload", {}, options);
  }

  wait(parameters: WaitParameters = {}, options?: CommandOptions): Promise<CommandResult<"wait">> {
    return this.invoke("wait", parameters, options);
  }

  tour(parameters: TourParameters = {}, options?: CommandOptions): Promise<CommandResult<"tour">> {
    return this.invoke("tour", parameters, options);
  }

  captureInfo(options?: CommandOptions): Promise<CommandResult<"capture.info">> {
    return this.invoke("capture.info", {}, options);
  }

  screenshot(parameters: ScreenshotParameters = {}, options?: CommandOptions): Promise<CommandResult<"screenshot">> {
    return this.invoke("screenshot", parameters, options);
  }

  recordStart(parameters: RecordStartParameters = {}, options?: CommandOptions): Promise<CommandResult<"record.start">> {
    return this.invoke("record.start", parameters, options);
  }

  recordStatus(options?: CommandOptions): Promise<CommandResult<"record.status">> {
    return this.invoke("record.status", {}, options);
  }

  recordStop(parameters: RecordStopParameters = {}, options?: CommandOptions): Promise<CommandResult<"record.stop">> {
    return this.invoke("record.stop", parameters, options);
  }

  qaReport(options?: CommandOptions): Promise<CommandResult<"qa.report">> {
    return this.invoke("qa.report", {}, options);
  }

  qaClear(options?: CommandOptions): Promise<CommandResult<"qa.clear">> {
    return this.invoke("qa.clear", {}, options);
  }

  consoleList(parameters: ConsoleListParameters = {}, options?: CommandOptions): Promise<CommandResult<"console.list">> {
    return this.invoke("console.list", parameters, options);
  }

  networkList(parameters: NetworkListParameters = {}, options?: CommandOptions): Promise<CommandResult<"network.list">> {
    return this.invoke("network.list", parameters, options);
  }

  networkGet(parameters: NetworkGetParameters, options?: CommandOptions): Promise<CommandResult<"network.get">> {
    return this.invoke("network.get", parameters, options);
  }

  stylesGet(parameters: StylesGetParameters = {}, options?: CommandOptions): Promise<CommandResult<"styles.get">> {
    return this.invoke("styles.get", parameters, options);
  }

  cookiesList(parameters: CookiesListParameters = {}, options?: CommandOptions): Promise<CommandResult<"cookies.list">> {
    return this.invoke("cookies.list", parameters, options);
  }

  storageList(parameters: StorageListParameters = {}, options?: CommandOptions): Promise<CommandResult<"storage.list">> {
    return this.invoke("storage.list", parameters, options);
  }

  visualCompare(parameters: VisualCompareParameters, options?: CommandOptions): Promise<CommandResult<"visual.compare">> {
    return this.invoke("visual.compare", parameters, options);
  }

  performanceGet(options?: CommandOptions): Promise<CommandResult<"performance.get">> {
    return this.invoke("performance.get", {}, options);
  }

  animationList(options?: CommandOptions): Promise<CommandResult<"animation.list">> {
    return this.invoke("animation.list", {}, options);
  }

  reportCreate(parameters: ReportCreateParameters = {}, options?: CommandOptions): Promise<CommandResult<"report.create">> {
    return this.invoke("report.create", parameters, options);
  }

  flowStart(options?: CommandOptions): Promise<CommandResult<"flow.start">> {
    return this.invoke("flow.start", {}, options);
  }

  flowStop(parameters: FlowStopParameters = {}, options?: CommandOptions): Promise<CommandResult<"flow.stop">> {
    return this.invoke("flow.stop", parameters, options);
  }

  flowRun(parameters: FlowRunParameters, options?: CommandOptions): Promise<CommandResult<"flow.run">> {
    return this.invoke("flow.run", parameters, options);
  }

  networkEmulate(parameters: NetworkEmulateParameters = {}, options?: CommandOptions): Promise<CommandResult<"network.emulate">> {
    return this.invoke("network.emulate", parameters, options);
  }

  networkMockSet(parameters: NetworkMockSetParameters, options?: CommandOptions): Promise<CommandResult<"network.mock.set">> {
    return this.invoke("network.mock.set", parameters, options);
  }

  networkMockClear(options?: CommandOptions): Promise<CommandResult<"network.mock.clear">> {
    return this.invoke("network.mock.clear", {}, options);
  }

  authLogin(parameters: AuthLoginParameters = {}, options?: CommandOptions): Promise<CommandResult<"auth.login">> {
    return this.invoke("auth.login", parameters, options);
  }

}

